### ISSUE TITLE
Single Hotswap emits error: "Can't setup hotswap task: Could not find class file in output path"

### ISSUE THREAD

**Issue by bruberu** [LabyStudio/singlehotswap#12]
I'm currently running a Gradle project based off of [CleanroomMC/TemplateDevEnv](https://github.com/CleanroomMC/TemplateDevEnv), and I found that this plugin would be useful for helping me create GUIs. However, whenever I attempt to run the hotswap, I immediately get the message "Can't setup hotswap task: Could not find class file in output path" in a balloon notification; indeed, I don't see any progress bar appear, although it may just disappear too quickly for me to see. No actual hotswap is performed in the process, either, nor does anything appear in the IntelliJ log.

I do run Ubuntu 22.04.02 LTS, and I have heard of others managing to run this on similar projects, so that may be a cause for concern here as well.

**Comment by brachy84** [comment]
Same issue here, but only in one project

**Comment by brachy84** [comment]
It seems, that you need to run the Project with IntelliJ and not Gradle. IntelliJ generates the compiler output path and stuff. Running once via IntelliJ and then with gradle works fine too.
A config to override the compile output maybe would be nice tho.

**Comment by gpierre35** [comment]
Same issue here, @brachy84 how do you process to change from Gradle to Intellif ?

**Comment by LabyStudio** [comment]
Hm, I just set up [TemplateDevEnv](https://github.com/CleanroomMC/TemplateDevEnv) and it worked the first time I tried to hotswap a file. Did I miss something?

**Comment by LabyStudio** [comment]
I mean, the plugin [tries to find ](https://github.com/LabyStudio/singlehotswap/blob/master/src/main/java/net/labymod/intellij/singlehotswap/hotswap/impl/AbstractContext.java#L54)the class files generated by the compiler to hotswap them.
Usually they are located in `build/classes/java/main/`

In your case, they might not exist or be located elsewhere?

**Comment by brachy84** [comment]
Sorry for the late reply.
Thats exactly where my classes are, but the plugin only searches in the `out/` path.

**Comment by LabyStudio** [comment]
It uses the IntelliJ API to get the output path from the project module [here](https://github.com/LabyStudio/singlehotswap/blob/master/src/main/java/net/labymod/intellij/singlehotswap/hotswap/impl/AbstractContext.java#L49).
The question is, why is it not returning the correct ones in your case? Can you reproduce it with a blank project setup?

**Comment by LabyStudio** [comment]
I just debugged `CompilerPaths#getOutputPaths` and it seems like in your case it never reaches the Gradle extension part of this code to get the `build/*` directory: ![image](https://github.com/LabyStudio/singlehotswap/assets/8986505/23a65278-2cd3-4dd5-9ad0-fc8ce1a14c42)

I'm still not able to reproduce it hm.

**Comment by brachy84** [comment]
I figured it out:

1. Make sure the the compiler output path is correct. It should end with `build/classes`
2. In IntelliJ go to Settings -> Build, Execution, Deployment -> Build Tools -> Gradle and set `Build and run using:` to `Gradle`

If both are set it works fine.
