### ISSUE TITLE
What is the Difference Between the Blue Hammer and the White Hammer?

### ISSUE THREAD

**Issue by bling-yshs** [LabyStudio/singlehotswap#19]
In the keymap, I've noticed there are two shortcuts. Could you please tell me the difference between the blue hammer and the white hammer? My IDEA version is 2024.1.
![image](https://github.com/LabyStudio/singlehotswap/assets/41812674/114f1e8d-dc4a-4c29-bcca-5ba5de6afb32)

**Comment by LabyStudio** [comment]
The blue hammer is for the old IntelliJ UI and the white one is for the new UI.
Interesting that you can see them both in the settings...

**Comment by bling-yshs** [comment]
> The blue hammer is for the old IntelliJ UI and the white one is for the new UI. Interesting that you can see them both in the settings...

Okay, thank you ❤
