### ISSUE TITLE
Hotswap has compilation error when none are there.

### ISSUE THREAD

**Issue by JoeTheOrangeCat** [LabyStudio/singlehotswap#22]
When Build and run is set top IntelliJ it give this error: compilation `Could not find class file in output path. Are you using the wrong compiler?`

And when I use Gradle it gives `Hot Swap failed Gronk [runClient]: Error during hotswap: Compilation fails`
This is a fabric mod, and the option to run hotswap shows up even when no changes were made.

This project is set up on git.

It didn't always do this, Please help.

https://github.com/user-attachments/assets/e6eae201-ca55-4181-99d8-e2b06693a4aa

Previously it had errors, which I believed were due to errors in mixins(The mixins were fine but for some reason showed up as an error) But this has all mixins disabled and commented out.

**Comment by JoeTheOrangeCat** [comment]
Issue seems to have been fixed after IDE has been updated

**Comment by LabyStudio** [comment]
Interesting... Let me know if it happens again because I don't know how to reproduce it

**Comment by LabyStudio** [comment]
Can you send me the link to the git repository if its public?

**Comment by JoeTheOrangeCat** [comment]
> Can you send me the link to the git repository if its public?

Hi! Sorry its not public yet, but I don't think it's to do with the code, I was using the 2022 version of IntelliJ and updating to the current one fixed it. Thank you so much for the quick reply though!

Also Mixins are working now too
