### ISSUE TITLE
Does not work with jabel plugin using java 16 syntax

### ISSUE THREAD

**Issue by gamerYToff** [LabyStudio/singlehotswap#24]
In my tests, when I tried to perform hotswap while using the Jabel plugin to use Java 16 syntax in a Java 8 project, I always got a compilation failure error.

**Comment by LabyStudio** [comment]
I don't think its possible but you could try to disable "Use Built-In Compiler" in the Single Hotswap settings

**Comment by gamerYToff** [comment]
> I don't think its possible but you could try to disable "Use Built-In Compiler" in the Single Hotswap settings

Thank you very much, this works, such a simple thing... saved my code!
