### ISSUE TITLE
Single hotswap not available for PsiJavaFileImpl

### ISSUE THREAD

**Issue by ahmednrana** [LabyStudio/singlehotswap#4]
Hi,

The single hotswap button is disabled. 
On Mouse over, it says **Single hotswap (not available for PsiJavaFileImpl)**

**Comment by LabyStudio** [comment]
Hey, is your java plugin (com.intellij.java) installed?

I can imagine that it throws an exception at
https://github.com/LabyStudio/singlehotswap/blob/master/src/main/java/net/labymod/intellij/singlehotswap/hotswap/EnumFileType.java#L58

Do you have any logs or can you debug it somehow?

This check definitely fails:
https://github.com/LabyStudio/singlehotswap/blob/master/src/main/java/net/labymod/intellij/singlehotswap/actions/SingleHotswapAction.java#L68
